# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000

create_project -in_memory -part xc7a50ticsg325-1L
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Rajat Raj/Desktop/4th SEM Notes/Approximate Multiplier Design/ExistMul/existing method/Existing Mehod/Existing Mehod.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Rajat Raj/Desktop/4th SEM Notes/Approximate Multiplier Design/ExistMul/existing method/Existing Mehod/Existing Mehod.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  {C:/Users/Rajat Raj/Desktop/4th SEM Notes/Approximate Multiplier Design/ExistMul/existing method/ha.v}
  {C:/Users/Rajat Raj/Desktop/4th SEM Notes/Approximate Multiplier Design/ExistMul/existing method/fa.v}
  {C:/Users/Rajat Raj/Desktop/4th SEM Notes/Approximate Multiplier Design/ExistMul/existing method/conventional_4to2compressor.v}
  {C:/Users/Rajat Raj/Desktop/4th SEM Notes/Approximate Multiplier Design/ExistMul/existing method/exact_16x16_mul.v}
}
catch { write_hwdef -file exact_16x16_mul.hwdef }
synth_design -top exact_16x16_mul -part xc7a50ticsg325-1L
write_checkpoint -noxdef exact_16x16_mul.dcp
catch { report_utilization -file exact_16x16_mul_utilization_synth.rpt -pb exact_16x16_mul_utilization_synth.pb }
